document.addEventListener("DOMContentLoaded", () => {
  renderNavbar(); renderFooter(); renderTestDriveModal(); bindGlobalForms();
  if (document.getElementById("featuredCars")) renderFeatured();
  if (document.getElementById("brandGrid")) renderBrandPreview();
  populateSelect("quickBrand", brands.map(b => b.name));
  populateSelect("quickCategory", [...new Set(cars.map(c => c.category))]);
});

function renderNavbar() {
  const path = location.pathname.split("/").pop() || "index.html";
  document.getElementById("navbar").innerHTML = `<nav class="navbar navbar-expand-lg sticky-top"><div class="container">
 <a class="navbar-brand" href="index.html"><span class="logo-mark">V</span> Velora Motors</a>
 <button class="navbar-toggler" data-bs-toggle="collapse" data-bs-target="#navMenu"><span class="navbar-toggler-icon"></span></button>
 <div class="collapse navbar-collapse" id="navMenu"><ul class="navbar-nav ms-auto align-items-lg-center">
 ${navLink("index.html", "Home", path)}${navLink("cars.html", "Cars", path)}${navLink("brands.html", "Brands", path)}${navLink("offers.html", "Offers", path)}${navLink("about.html", "About", path)}${navLink("services.html", "Services", path)}${navLink("gallery.html", "Gallery", path)}${navLink("contact.html", "Contact", path)}
 <li class="nav-item ms-lg-2"><a class="btn btn-primary btn-sm" href="login.html"><i class="bi bi-person"></i> Login</a></li></ul></div></div></nav>`;
}
function navLink(h, t, p) { return `<li class="nav-item"><a class="nav-link ${p === h ? "active" : ""}" href="${h}">${t}</a></li>` }
function renderFooter() {
  document.getElementById("footer").innerHTML = `<footer class="footer"><div class="container"><div class="row g-4"><div class="col-lg-4"><a class="navbar-brand text-white" href="index.html"><span class="logo-mark">V</span> Velora Motors</a><p class="mt-3">A premium automotive destination for new and pre-owned vehicles, finance, service and a better ownership experience.</p><div class="d-flex gap-3 mt-3"><a href="#"><i class="bi bi-instagram"></i></a><a href="#"><i class="bi bi-facebook"></i></a><a href="#"><i class="bi bi-youtube"></i></a><a href="#"><i class="bi bi-linkedin"></i></a></div></div><div class="col-6 col-lg-2"><h5>Explore</h5><div class="d-grid gap-2 mt-3"><a href="cars.html">Cars</a><a href="brands.html">Brands</a><a href="offers.html">Offers</a><a href="gallery.html">Gallery</a></div></div><div class="col-6 col-lg-2"><h5>Company</h5><div class="d-grid gap-2 mt-3"><a href="about.html">About</a><a href="services.html">Services</a><a href="contact.html">Contact</a><a href="login.html">Login</a></div></div><div class="col-lg-4"><h5>Visit our showroom</h5><p class="mt-3 mb-1">42 Automotive Avenue, Bengaluru, Karnataka</p><p class="mb-1">+91 98765 43210</p><p>hello@veloramotors.com</p></div></div><div class="footer-bottom d-flex flex-wrap justify-content-between"><span>© 2026 Velora Motors. All rights reserved.</span><span>Privacy · Terms · Cookie Policy</span></div></div></footer>`;
}
function renderTestDriveModal() {
  const mount = document.getElementById("testDriveMount"); if (!mount) return;
  mount.innerHTML = `<div class="modal fade" id="testDriveModal" tabindex="-1"><div class="modal-dialog modal-lg modal-dialog-centered"><div class="modal-content"><div class="modal-header"><div><span class="section-kicker">TEST DRIVE</span><h5 class="mb-0">Book your drive</h5></div><button class="btn-close" data-bs-dismiss="modal"></button></div><form id="testDriveForm"><div class="modal-body row g-3"><div class="col-md-6"><label class="form-label">Full Name</label><input name="name" class="form-control" required></div><div class="col-md-6"><label class="form-label">Phone</label><input name="phone" class="form-control" required></div><div class="col-12"><label class="form-label">Choose Vehicle</label><select name="car" id="testDriveCar" class="form-select" required><option value="">Select a vehicle</option>${cars.map(c => `<option>${c.name}</option>`).join("")}</select></div><div class="col-md-6"><label class="form-label">Preferred Date</label><input name="date" type="date" class="form-control" required></div><div class="col-md-6"><label class="form-label">Preferred Time</label><select name="time" class="form-select" required><option>10:00 AM</option><option>11:30 AM</option><option>01:00 PM</option><option>03:00 PM</option><option>05:00 PM</option><option>06:30 PM</option></select></div><div class="col-12"><label class="form-label">Message (optional)</label><textarea name="message" class="form-control" rows="3" placeholder="Any preferences or questions?"></textarea></div></div><div class="modal-footer"><button type="button" class="btn btn-light" data-bs-dismiss="modal">Cancel</button><button class="btn btn-primary">Confirm Test Drive <i class="bi bi-arrow-right"></i></button></div></form></div></div></div>`;
  document.getElementById("testDriveForm").addEventListener("submit", e => { e.preventDefault(); bootstrap.Modal.getInstance(document.getElementById("testDriveModal")).hide(); showToast("Test drive request submitted successfully."); e.target.reset(); });
}
function bindGlobalForms() {
  const q = document.getElementById("quickSearchForm"); if (q) q.addEventListener("submit", e => { e.preventDefault(); const p = new URLSearchParams(); const b = document.getElementById("quickBrand").value, c = document.getElementById("quickCategory").value, bud = document.getElementById("quickBudget").value; if (b) p.set("brand", b); if (c) p.set("category", c); if (bud) p.set("budget", bud); location.href = "cars.html?" + p.toString() });
  const cf = document.getElementById("contactForm"); if (cf) cf.addEventListener("submit", e => { e.preventDefault(); showToast("Thanks! Your message has been sent. Our team will contact you shortly."); cf.reset() });
}
function populateSelect(id, arr) { const el = document.getElementById(id); if (el) arr.forEach(x => el.insertAdjacentHTML("beforeend", `<option value="${x}">${x}</option>`)) }
function renderFeatured() { document.getElementById("featuredCars").innerHTML = cars.filter(c => c.featured).slice(0, 4).map(carCard).join("") }
function renderBrandPreview() { document.getElementById("brandGrid").innerHTML = brands.slice(0, 6).map(brand => `<div class="col-6 col-md-4 col-lg-2"><a href="cars.html?brand=${encodeURIComponent(brand.name)}" class="brand-card d-block"><div class="brand-logo">${brand.short}</div><h5>${brand.name}</h5><small class="text-secondary">${brand.count} vehicles</small></a></div>`).join("") }
function renderAllBrands() { document.getElementById("allBrands").innerHTML = brands.map(b => `<div class="col-sm-6 col-lg-4"><a href="cars.html?brand=${encodeURIComponent(b.name)}" class="brand-card bg-light text-dark d-block border"><div class="brand-logo">${b.short}</div><h4>${b.name}</h4><p class="text-muted mb-2">${b.desc}</p><span class="text-link">${b.count} vehicles <i class="bi bi-arrow-right"></i></span></a></div>`).join("") }
function renderOffers() { document.getElementById("offerGrid").innerHTML = offers.map(o => `<div class="col-12"><article class="offer-card"><img src="${o.image}" alt="${o.title}"><div class="offer-content"><span class="offer-tag">${o.tag}</span><h3>${o.title}</h3><p>${o.desc}</p><button class="btn btn-light" data-bs-toggle="modal" data-bs-target="#testDriveModal">Enquire Now <i class="bi bi-arrow-right"></i></button></div></article></div>`).join("") }
function carCard(c) { return `<div class="col-md-6 col-lg-3"><article class="car-card"><img class="car-image" src="${c.image}" alt="${c.name}" loading="lazy"><div class="car-body"><div class="d-flex justify-content-between align-items-center"><span class="badge-soft">${c.category}</span><span class="text-muted small">${c.year}</span></div><h3 class="car-title">${c.name}</h3><div class="car-meta"><span><i class="bi bi-fuel-pump"></i> ${c.fuel}</span><span><i class="bi bi-speedometer2"></i> ${c.km}</span></div><div class="d-flex justify-content-between align-items-center mt-4"><span class="price">₹${c.price} Lakh</span><button class="btn btn-sm btn-outline-dark" onclick="openTestDrive('${c.name.replaceAll("'", "\\'")}')">Test Drive</button></div></div></article></div>` }
function openTestDrive(name) { const m = document.getElementById("testDriveModal"); if (!m) return; const sel = document.getElementById("testDriveCar"); if (sel) sel.value = name; new bootstrap.Modal(m).show() }
function showToast(message) { let mount = document.getElementById("toastMount"); if (!mount) return; mount.innerHTML = `<div class="toast-container position-fixed bottom-0 end-0 p-4"><div class="toast show text-bg-dark border-0"><div class="d-flex"><div class="toast-body"><i class="bi bi-check-circle text-success me-2"></i>${message}</div><button class="btn-close btn-close-white me-2 m-auto" data-bs-dismiss="toast"></button></div></div></div>`; setTimeout(() => mount.innerHTML = "", 4500) }