let compareIds = [];
document.addEventListener("DOMContentLoaded", () => {
    populateSelect("brandFilter", brands.map(b => b.name)); populateSelect("categoryFilter", [...new Set(cars.map(c => c.category))]);
    const params = new URLSearchParams(location.search); if (params.get("brand")) document.getElementById("brandFilter").value = params.get("brand"); if (params.get("category")) document.getElementById("categoryFilter").value = params.get("category");
    ["searchInput", "brandFilter", "categoryFilter", "fuelFilter", "sortFilter"].forEach(id => document.getElementById(id).addEventListener("input", renderCars));
    document.getElementById("carFilterForm").addEventListener("reset", () => setTimeout(renderCars, 0)); document.getElementById("compareBtn").addEventListener("click", () => showToast("Comparison preview: " + compareIds.map(id => cars.find(c => c.id === id)?.name).join(" vs ")));
    renderCars();
});
function renderCars() {
    let list = [...cars]; const s = document.getElementById("searchInput").value.toLowerCase(), b = document.getElementById("brandFilter").value, c = document.getElementById("categoryFilter").value, f = document.getElementById("fuelFilter").value, sort = document.getElementById("sortFilter").value;
    if (s) list = list.filter(x => (x.name + x.brand + x.category).toLowerCase().includes(s)); if (b) list = list.filter(x => x.brand === b); if (c) list = list.filter(x => x.category === c); if (f) list = list.filter(x => x.fuel === f);
    if (new URLSearchParams(location.search).get("budget")) { const q = new URLSearchParams(location.search).get("budget"); list = list.filter(x => q === "under20" ? x.price < 20 : q === "20to40" ? x.price >= 20 && x.price <= 40 : q === "40to70" ? x.price > 40 && x.price <= 70 : x.price > 70) }
    if (sort === "low") list.sort((a, b) => a.price - b.price); if (sort === "high") list.sort((a, b) => b.price - a.price); if (sort === "name") list.sort((a, b) => a.name.localeCompare(b.name));
    document.getElementById("resultCount").textContent = `Showing ${list.length} of ${cars.length} vehicles`; document.getElementById("carGrid").innerHTML = list.map(c => carCardWithCompare(c)).join(""); document.getElementById("emptyState").classList.toggle("d-none", list.length > 0);
}
function carCardWithCompare(c) { return `<div class="col-md-6 col-lg-4 col-xl-3"><article class="car-card"><label class="compare-check"><input type="checkbox" ${compareIds.includes(c.id) ? "checked" : ""} onchange="toggleCompare(${c.id},this.checked)"> Compare</label><img class="car-image" src="${c.image}" alt="${c.name}" loading="lazy"><div class="car-body"><div class="d-flex justify-content-between"><span class="badge-soft">${c.category}</span><span class="status ${c.status === "Available" ? "available" : "sold"}">${c.status}</span></div><h3 class="car-title">${c.name}</h3><div class="car-meta"><span>${c.fuel}</span><span>${c.transmission}</span><span>${c.km}</span></div><div class="d-flex justify-content-between align-items-center mt-4"><span class="price">₹${c.price} Lakh</span><button class="btn btn-sm btn-outline-dark" onclick="openTestDrive('${c.name.replaceAll("'", "\\'")}')">Book Drive</button></div></div></article></div>` }
function toggleCompare(id, on) { if (on && compareIds.length >= 3) { showToast("You can compare up to 3 vehicles."); renderCars(); return } compareIds = on ? [...compareIds, id] : compareIds.filter(x => x !== id); document.getElementById("compareCount").textContent = compareIds.length; document.getElementById("compareBtn").disabled = compareIds.length < 2 }